//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv_my_ms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LY_DBEntities : DbContext
    {
        public LY_DBEntities()
            : base("name=LY_DBEntities")
        {
            this.Database.CommandTimeout = 2*60*1000; //时间单位是毫秒
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mv_error_log> mv_error_log { get; set; }
    
        public virtual ObjectResult<Nullable<long>> mv_mysql_data_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("mv_mysql_data_count");
        }
    
        public virtual int mv_mysql_data(string createtable, Nullable<int> pageindex, Nullable<int> pagesize)
        {
            var createtableParameter = createtable != null ?
                new ObjectParameter("createtable", createtable) :
                new ObjectParameter("createtable", typeof(string));
    
            var pageindexParameter = pageindex.HasValue ?
                new ObjectParameter("pageindex", pageindex) :
                new ObjectParameter("pageindex", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("mv_mysql_data", createtableParameter, pageindexParameter, pagesizeParameter);
        }
    }
}
