//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv_my_ms
{
    using System;
    using System.Collections.Generic;
    
    public partial class mv_error_log
    {
        public int Id { get; set; }
        public long pageindex { get; set; }
        public string error_msg { get; set; }
        public bool isdispose { get; set; }
        public int count { get; set; }
        public int sleep { get; set; }
    }
}
