//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirst
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class B_User
    {
    /// <summary>
    /// 
    /// </summary>
        public int Id { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public int CaregoryId { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Address { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Phone { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Email { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Remark { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string CreateById { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public System.DateTime CreateDate { get; set; }
    }
}
