//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YTDBEntities : DbContext
    {
        public YTDBEntities()
            : base("name=YTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<B_Caregory> B_Caregory { get; set; }
        public virtual DbSet<B_User> B_User { get; set; }
        public virtual DbSet<OJT_Details> OJT_Details { get; set; }
        public virtual DbSet<OJT_Examination_Paper_Master> OJT_Examination_Paper_Master { get; set; }
        public virtual DbSet<OJT_Examination_Paper_Type> OJT_Examination_Paper_Type { get; set; }
        public virtual DbSet<OJT_Master> OJT_Master { get; set; }
        public virtual DbSet<OJT_Question_Master> OJT_Question_Master { get; set; }
        public virtual DbSet<OJT_Question_Option> OJT_Question_Option { get; set; }
        public virtual DbSet<OJT_Question_Type> OJT_Question_Type { get; set; }
        public virtual DbSet<OJT_User_Score_Details> OJT_User_Score_Details { get; set; }
        public virtual DbSet<OJT_User_Score_Master> OJT_User_Score_Master { get; set; }
    }
}
