//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirst
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 
    /// </summary>
    public partial class OJT_Question_Type
    {
    /// <summary>
    /// 
    /// </summary>
        public int Id { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Title { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public int IsDelete { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string CreatedBy { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public Nullable<System.DateTime> CreatedDate { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string ModifiedBy { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    /// <summary>
    /// 
    /// </summary>
        public string Remark { get; set; }
    }
}
