//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI2019725.WebOneService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebOneService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorld0Result 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld0", ReplyAction="*")]
        WEBAPI2019725.WebOneService.HelloWorld0Response HelloWorld0(WEBAPI2019725.WebOneService.HelloWorld0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld0", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPI2019725.WebOneService.HelloWorld0Response> HelloWorld0Async(WEBAPI2019725.WebOneService.HelloWorld0Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld0Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld0", Namespace="http://tempuri.org/", Order=0)]
        public WEBAPI2019725.WebOneService.HelloWorld0RequestBody Body;
        
        public HelloWorld0Request() {
        }
        
        public HelloWorld0Request(WEBAPI2019725.WebOneService.HelloWorld0RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld0RequestBody {
        
        public HelloWorld0RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld0Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld0Response", Namespace="http://tempuri.org/", Order=0)]
        public WEBAPI2019725.WebOneService.HelloWorld0ResponseBody Body;
        
        public HelloWorld0Response() {
        }
        
        public HelloWorld0Response(WEBAPI2019725.WebOneService.HelloWorld0ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld0ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld0Result;
        
        public HelloWorld0ResponseBody() {
        }
        
        public HelloWorld0ResponseBody(string HelloWorld0Result) {
            this.HelloWorld0Result = HelloWorld0Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WEBAPI2019725.WebOneService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WEBAPI2019725.WebOneService.WebService1Soap>, WEBAPI2019725.WebOneService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEBAPI2019725.WebOneService.HelloWorld0Response WEBAPI2019725.WebOneService.WebService1Soap.HelloWorld0(WEBAPI2019725.WebOneService.HelloWorld0Request request) {
            return base.Channel.HelloWorld0(request);
        }
        
        public string HelloWorld0() {
            WEBAPI2019725.WebOneService.HelloWorld0Request inValue = new WEBAPI2019725.WebOneService.HelloWorld0Request();
            inValue.Body = new WEBAPI2019725.WebOneService.HelloWorld0RequestBody();
            WEBAPI2019725.WebOneService.HelloWorld0Response retVal = ((WEBAPI2019725.WebOneService.WebService1Soap)(this)).HelloWorld0(inValue);
            return retVal.Body.HelloWorld0Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEBAPI2019725.WebOneService.HelloWorld0Response> WEBAPI2019725.WebOneService.WebService1Soap.HelloWorld0Async(WEBAPI2019725.WebOneService.HelloWorld0Request request) {
            return base.Channel.HelloWorld0Async(request);
        }
        
        public System.Threading.Tasks.Task<WEBAPI2019725.WebOneService.HelloWorld0Response> HelloWorld0Async() {
            WEBAPI2019725.WebOneService.HelloWorld0Request inValue = new WEBAPI2019725.WebOneService.HelloWorld0Request();
            inValue.Body = new WEBAPI2019725.WebOneService.HelloWorld0RequestBody();
            return ((WEBAPI2019725.WebOneService.WebService1Soap)(this)).HelloWorld0Async(inValue);
        }
    }
}
