//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.W_Service.WebService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="xxxxxxxxxx", ConfigurationName="WebService1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 xxxxxxxxxx 的元素名称 HelloWorldsResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/HelloWorlds", ReplyAction="*")]
        LY.W_Service.WebService1.HelloWorldsResponse HelloWorlds(LY.W_Service.WebService1.HelloWorldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/HelloWorlds", ReplyAction="*")]
        System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldsResponse> HelloWorldsAsync(LY.W_Service.WebService1.HelloWorldsRequest request);
        
        // CODEGEN: 命名空间 xxxxxxxxxx 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/HelloWorld", ReplyAction="*")]
        LY.W_Service.WebService1.HelloWorldResponse HelloWorld(LY.W_Service.WebService1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldResponse> HelloWorldAsync(LY.W_Service.WebService1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/insertCargoInfo", ReplyAction="*")]
        int insertCargoInfo(int Cname, int Cnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="xxxxxxxxxx/insertCargoInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertCargoInfoAsync(int Cname, int Cnum);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorlds", Namespace="xxxxxxxxxx", Order=0)]
        public LY.W_Service.WebService1.HelloWorldsRequestBody Body;
        
        public HelloWorldsRequest() {
        }
        
        public HelloWorldsRequest(LY.W_Service.WebService1.HelloWorldsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldsRequestBody {
        
        public HelloWorldsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldsResponse", Namespace="xxxxxxxxxx", Order=0)]
        public LY.W_Service.WebService1.HelloWorldsResponseBody Body;
        
        public HelloWorldsResponse() {
        }
        
        public HelloWorldsResponse(LY.W_Service.WebService1.HelloWorldsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="xxxxxxxxxx")]
    public partial class HelloWorldsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldsResult;
        
        public HelloWorldsResponseBody() {
        }
        
        public HelloWorldsResponseBody(string HelloWorldsResult) {
            this.HelloWorldsResult = HelloWorldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="xxxxxxxxxx", Order=0)]
        public LY.W_Service.WebService1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LY.W_Service.WebService1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="xxxxxxxxxx", Order=0)]
        public LY.W_Service.WebService1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LY.W_Service.WebService1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="xxxxxxxxxx")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : LY.W_Service.WebService1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<LY.W_Service.WebService1.WebService1Soap>, LY.W_Service.WebService1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LY.W_Service.WebService1.HelloWorldsResponse LY.W_Service.WebService1.WebService1Soap.HelloWorlds(LY.W_Service.WebService1.HelloWorldsRequest request) {
            return base.Channel.HelloWorlds(request);
        }
        
        public string HelloWorlds() {
            LY.W_Service.WebService1.HelloWorldsRequest inValue = new LY.W_Service.WebService1.HelloWorldsRequest();
            inValue.Body = new LY.W_Service.WebService1.HelloWorldsRequestBody();
            LY.W_Service.WebService1.HelloWorldsResponse retVal = ((LY.W_Service.WebService1.WebService1Soap)(this)).HelloWorlds(inValue);
            return retVal.Body.HelloWorldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldsResponse> LY.W_Service.WebService1.WebService1Soap.HelloWorldsAsync(LY.W_Service.WebService1.HelloWorldsRequest request) {
            return base.Channel.HelloWorldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldsResponse> HelloWorldsAsync() {
            LY.W_Service.WebService1.HelloWorldsRequest inValue = new LY.W_Service.WebService1.HelloWorldsRequest();
            inValue.Body = new LY.W_Service.WebService1.HelloWorldsRequestBody();
            return ((LY.W_Service.WebService1.WebService1Soap)(this)).HelloWorldsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LY.W_Service.WebService1.HelloWorldResponse LY.W_Service.WebService1.WebService1Soap.HelloWorld(LY.W_Service.WebService1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LY.W_Service.WebService1.HelloWorldRequest inValue = new LY.W_Service.WebService1.HelloWorldRequest();
            inValue.Body = new LY.W_Service.WebService1.HelloWorldRequestBody();
            LY.W_Service.WebService1.HelloWorldResponse retVal = ((LY.W_Service.WebService1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldResponse> LY.W_Service.WebService1.WebService1Soap.HelloWorldAsync(LY.W_Service.WebService1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LY.W_Service.WebService1.HelloWorldResponse> HelloWorldAsync() {
            LY.W_Service.WebService1.HelloWorldRequest inValue = new LY.W_Service.WebService1.HelloWorldRequest();
            inValue.Body = new LY.W_Service.WebService1.HelloWorldRequestBody();
            return ((LY.W_Service.WebService1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int insertCargoInfo(int Cname, int Cnum) {
            return base.Channel.insertCargoInfo(Cname, Cnum);
        }
        
        public System.Threading.Tasks.Task<int> insertCargoInfoAsync(int Cname, int Cnum) {
            return base.Channel.insertCargoInfoAsync(Cname, Cnum);
        }
    }
}
